name: Build luci-app-openlist for OpenWrt

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Download ImmortalWRT SDK
      run: |
        wget https://downloads.immortalwrt.org/releases/24.10.2/targets/x86/64/immortalwrt-sdk-24.10.2-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz
        tar -xvf immortalwrt-sdk-*.tar.xz
        mv immortalwrt-sdk-* sdk

    - name: Prepare SDK
      run: |
        cd sdk
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        make defconfig

    - name: Copy luci-app-openlist to SDK
      run: |
        cp -r ./luci-app-openlist ./sdk/package/

    - name: Build luci-app-openlist
      run: |
        cd sdk
        make package/luci-app-openlist/compile V=s -j$(nproc)

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: luci-app-openlist-ipk
        path: |
          sdk/bin/packages/**/luci-app-openlist_*.ipk
